name: Readme Connect 4

on:
  issues:
    types: [opened]
  workflow_dispatch:

# Explicitly grant permission to update the README and manage issues
permissions:
  contents: write
  issues: write

jobs:
  play:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'readme-connect-4') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: rossjrw/readme-connect-4@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
